VERILOG = ../src/top/zx81_ulx4m.v \
    ../src/sys/ecp5pll.sv ../src/sys/ps2.v ../src/sys/hdmi.v \
    ../src/sys/scandoubler.v \
    ../src/fpga_zx81.v ../src/memory.v ../src/keyboard.v \
    ../src/cpu/tv80n.v ../src/cpu/tv80_core.v ../src/cpu/tv80_alu.v \
    ../src/cpu/tv80_reg.v ../src/cpu/tv80_mcode.v

PIN_DEF = ulx4m_v002.lpf
TOP = zx81

include ulx4m.mk

