VERILOG = ../src/top/zx81_ulx3s_vga.v \
    ../src/sys/pll.v ../src/sys/ps2.v ../src/sys/hdmi.v \
    ../src/sys/scandoubler.v \
    ../src/fpga_zx81.v ../src/memory.v ../src/keyboard.v \
    ../src/cpu/tv80n.v ../src/cpu/tv80_core.v ../src/cpu/tv80_alu.v \
    ../src/cpu/tv80_reg.v ../src/cpu/tv80_mcode.v

PIN_DEF = ulx3s_zx81.lpf

include ulx3s.mk

